### ISSUE TITLE
pat02-multisensor unsupported

### ISSUE THREAD

**Issue by trycoon** [whizzosoftware/WZWave#12]
http://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1352/PAT02-NS_Manual.pdf

When I try to include a pat02-multisensor the inclusion works but it later fails when loading node-information:

Native lib Version = RXTX-2.2pre2
Java lib Version   = RXTX-2.1-7
WARNING:  RXTX Version mismatch
	Jar version = RXTX-2.1-7
	native lib Version = RXTX-2.2pre2
ControllerInfo received: libraryVersion=Z-Wave 3.99, homeId=-6612895, nodeId=1
Z-Wave node added: 1
Please set Zwave devices to inclusion-mode...
onZWaveInclusion, nodeInfo.getBasicDeviceClass=4, nodeInfo.getGenericDeviceClass=7, nodeInfo.getSpecificDeviceClass=1, success=true

^^^^^^ successful inclusion, but:

2016-12-10 12:33:01,724 [pool-2-thread-1] ERROR com.whizzosoftware.wzwave.controller.netty.NettyZWaveController - Unable to create node
com.whizzosoftware.wzwave.node.NodeCreationException: Unable to create node 2 due to unknown generic device class: 0x07
	at com.whizzosoftware.wzwave.node.ZWaveNodeFactory.createNode(ZWaveNodeFactory.java:90) ~[zwavebinder-1.0.0.jar:?]
	at com.whizzosoftware.wzwave.controller.netty.NettyZWaveController.onNodeProtocolInfo(NettyZWaveController.java:233) [zwavebinder-1.0.0.jar:?]
	at com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler.processNodeProtocolInfo(ZWaveChannelInboundHandler.java:99) [zwavebinder-1.0.0.jar:?]
	at com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler.channelRead(ZWaveChannelInboundHandler.java:48) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [zwavebinder-1.0.0.jar:?]
	at com.whizzosoftware.wzwave.channel.ZWaveDataFrameTransactionInboundHandler.channelRead(ZWaveDataFrameTransactionInboundHandler.java:80) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [zwavebinder-1.0.0.jar:?]
	at com.whizzosoftware.wzwave.channel.AcknowledgementInboundHandler.channelRead(AcknowledgementInboundHandler.java:31) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [zwavebinder-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:147) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:45) [zwavebinder-1.0.0.jar:?]
	at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:53) [zwavebinder-1.0.0.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [zwavebinder-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by whizzosoftware** [comment]
Thanks for the report. I'll take a look at it and see what's going on.

**Comment by Ziver** [comment]
Hi,
I'm having a similar issue when getting node information but I dont get a exception, I'm using a Fibaro Metered Wall Plug.

```
1752 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT SendData(0x02)[SENSOR_ALARM_GET],null: 0x01 0x09 0x00 0x13 0x02 0x02 0x71 0x04 0x05 0x05 0x90
1752 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler  - User event received: com.whizzosoftware.wzwave.channel.event.TransactionStartedEvent@38ba6e44
1753 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.commandclass.BinarySwitchCommandClass  - Received updated isOn (false)
1754 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x06
1757 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01
1757 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x04 0x01 0x13 0x01 0xE8
1757 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
1772 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01 0x07 0x00 0x13 0x05 0x00
1773 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x00 0x01 0xEF
1773 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
4774 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.frame.transaction.SendDataTransaction  - Transaction c2db3348-b9bc-4152-8945-d4cd4b88a602 has failed - will reset and resend initial request


4775 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT SendData(0x02)[SENSOR_ALARM_GET],null: 0x01 0x09 0x00 0x13 0x02 0x02 0x71 0x04 0x05 0x05 0x90
4775 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x06
4779 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01
4779 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x04 0x01 0x13 0x01 0xE8
4779 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
4794 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01 0x07 0x00 0x13 0x05 0x00 0x00 0x02 0xEC
4794 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.frame.transaction.SendDataTransaction  - Exceeded max transaction resends
7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler  - User event received: com.whizzosoftware.wzwave.channel.event.TransactionFailedEvent@1d3f0b37


7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT SendData(0x02)[SENSOR_MULTILEVEL_GET],null: 0x01 0x09 0x00 0x13 0x02 0x02 0x31 0x04 0x05 0x06 0xD3
7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x06
7811 [pool-1-thread-1] WARN com.whizzosoftware.wzwave.frame.transaction.SendDataTransaction  - Received unexpected frame for STATE_REQUEST_RECEIVED: ACK
7811 [pool-1-thread-1] ERROR com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler  - Received unknown data frame: ACK
7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01
7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x04 0x01 0x13 0x01 0xE8
7811 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
7811 [pool-1-thread-1] WARN com.whizzosoftware.wzwave.frame.transaction.SendDataTransaction  - Received unexpected frame for STATE_REQUEST_RECEIVED: SendData(0x00)
7811 [pool-1-thread-1] ERROR com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler  - Received unknown data frame: SendData(0x00)
7827 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01
7827 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x07 0x00 0x13 0x06 0x00 0x00 0x02 0xEF
7827 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
7827 [pool-1-thread-1] WARN com.whizzosoftware.wzwave.frame.transaction.SendDataTransaction  - Received unexpected frame for STATE_REQUEST_RECEIVED: SendData(0x06)[],2
7827 [pool-1-thread-1] ERROR com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler  - Received unknown data frame: SendData(0x06)[],2
7842 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x01
7842 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameDecoder  - RCVD: 0x0C 0x00 0x04 0x00 0x02 0x06 0x31 0x05 0x04 0x22 0x00 0x00 0xE1
7842 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.codec.ZWaveFrameEncoder  - SENT ACK: 0x06
7842 [pool-1-thread-1] DEBUG com.whizzosoftware.wzwave.channel.ZWaveChannelInboundHandler  - User event received: com.whizzosoftware.wzwave.channel.event.SendDataTransactionCompletedEvent@383e14cf
```

I've attached a log.
[log.txt](https://github.com/whizzosoftware/WZWave/files/1470875/log.txt)
